### PR TITLE
Change Management Server OS Requirement for 4.11 to Ubuntu 16.04

### PR DESCRIPTION
**Pull request by falcon78921**
Hello Apache CloudStack Community!

I noticed when I was installing ACS 4.11 on Ubuntu 14.04 that there are no packages available. In the Management Server Installation overview, I found that the Minimum OS requirements say this:

Operating system:
Preferred: CentOS/RHEL 7.2+, CentOS/RHEL 6.8+ or Ubuntu 14.04(.2) or higher

I changed the documentation in the _requirements.rst file, where it mentions Operating system, from Ubuntu 14.04(.2) to Ubuntu 16.04. 

If I'm missing anything in this pull request or need clarification, please let me know.

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
As far as I know Ubuntu 14 should be supported. It looks like during the version closing this was forgotten.
Let's see the feedback from others here.

Ping @DaanHoogland and @rhtyd

**Comment by rhtyd** [comment]
@rafaelweingartner I think 4.11 works with Ubuntu 14.04 /cc @PaulAngus 
I think we can support 14.04.5+ with ACS 4.11, perhaps in 4.12+ we can remove it. Can @falcon78921 test the repository against Ubuntu 14.04.5+ to confirm? (for repo you can use http://packages.shapeblue.com/cloudstack/upstream/debian/4.11/)

**Comment by rhtyd** [comment]
The issue seems to be with repository hosted on cloudstack.apt-get.eu @wido can you comment if you can support Ubuntu 14.04?

**Comment by wido** [comment]
@rhtyd I think it should work using sysvinit. I think there was an issue with building the packages. I'd have to look into that.

**Comment by falcon78921** [comment]
@rhtyd Yes, I'll try with Ubuntu 14.04.5 using the ShapeBlue packages

**Comment by falcon78921** [comment]
I saw someone uploaded packages for 4.11 on cloudstack.apt-get.eu. I used my ACS install script and pointed the sources to **deb http://cloudstack.apt-get.eu/ubuntu trusty 4.11**. 

ACS 4.11 appeared to have installed successfully, with no errors. I'll continue to test. Thanks! @wido @rhtyd @rafaelweingartner

**Comment by rafaelweingartner** [comment]
Welcome ;)
It was probably @wido who fixed things there. If everything is working for trusty, then we can close this PR.

**Comment by wido** [comment]
Yes, my bad for not mentioning it here. I figured out what went wrong during the build. It was a Java 7 <> 8 issue and that caused the packages not to be build for 4.11

I fixed that yesterday and uploaded them.

Btw, you can use https://download.cloudstack.org/

**Comment by falcon78921** [comment]
Thanks! @wido 

In the Management Server Installation [documentation](http://docs.cloudstack.apache.org/projects/cloudstack-installation/en/4.11/management-server/index.html), the source for Ubuntu packages is http://cloudstack.apt-get.eu/ubuntu. If https://download.cloudstack.org is also a viable option, may I suggest updating the documentation? It looks like https://download.cloudstack.org also points to http://cloudstack.apt-get.eu.

If not, I'll close out the PR.

**Comment by falcon78921** [comment]
Thanks again! :)

**Pull request closed without merging**
